### PR TITLE
Fix custom cookies getting overwritten

### LINKED ISSUE #909: Custom cookies get overriden by default value
### Version

6.5.4

### Platform

Any

### Steps to reproduce

When calling the constructor with a custom cookie like described in the readme:
```
using YoutubeExplode;

// Perform authentication and extract cookies
var cookies = ...;

// Cookie collection must be of type IReadOnlyList<System.Net.Cookie>
var youtube = new YoutubeClient(cookies);
```

any "SOCS" - cookie gets overwritten by the default value from the YouTubeHttpHandler

```
  _cookieContainer.Add(
            new Cookie("SOCS", "CAISEwgDEgk2NzM5OTg2ODUaAmVuIAEaBgiA6p23Bg")
            {
                Domain = "youtube.com",
            }
        );
```

### Details

Expected behavior: Custom Cookies remain in the HttpClient
Actual behavior: Custom Cookies get overwritten by default value

### Checklist

- [x] I have looked through existing issues to make sure that this bug has not been reported before
- [x] I have provided a descriptive title for this issue
- [x] I have made sure that this bug is reproducible on the latest version of the package
- [x] I have provided all the information needed to reproduce this bug as efficiently as possible
- [ ] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

### PR DESCRIPTION
**Pull request by Guacam-Ole**
To allow providing a custom Cookie like mentioned in the Authentication-part of the Readme:
```
using YoutubeExplode;

// Perform authentication and extract cookies
var cookies = ...;

// Cookie collection must be of type IReadOnlyList<System.Net.Cookie>
var youtube = new YoutubeClient(cookies);
``` 
That custom cookie must always have priority over the default/fallback cookie for this to work. I changed the order so to meet this requirement

Closes #909

### CODE REVIEW

File: YoutubeExplode/YoutubeHttpHandler.cs [hunk 1]
```diff
@@ -38,6 +34,10 @@ public YoutubeHttpHandler(
                 Domain = "youtube.com",
             }
         );
+
+        // Pre-fill cookies
```
Comment (Tyrrrz) [inline YoutubeExplode/YoutubeHttpHandler.cs:38]:
```suggestion
        // Add user-supplied cookies
```
