### PR TITLE
Get the batch of working playlist videos and stop on the unavailable batch

### LINKED ISSUE #921: Can't fetch a public playlist
### Version

v6.5.6

### Platform

.NET 9.0 / Windows 11

### Steps to reproduce

```csharp
var pl = await youtube.Playlists.GetAsync("youtube.com/playlist?list=PLz-YZsjoSww4AZGEeuJ2BwJ984_TCI0P1");
```

Image

### Details

Expected: playlist metadata

Actual: playlist unavailable

### Checklist

- [x] I have looked through existing issues to make sure that this bug has not been reported before
- [x] I have provided a descriptive title for this issue
- [x] I have made sure that this bug is reproducible on the latest version of the package
- [x] I have provided all the information needed to reproduce this bug as efficiently as possible
- [x] I have sponsored this project
- [ ] I have not read any of the above and just checked all the boxes to submit the issue

### PR DESCRIPTION
**Pull request by HossamSaberX**
Partially fixes #921 by handling unavailable playlist batches gracefully.

**Before:** Fetching crashed with `PlaylistUnavailableException` on any unavailable batch.

**After:** Catches the exception to stop enumeration without crashing. 

Note: In practice, unavailable batches omit all videos, so this prevents crashes but may still stop early.
We may think of further improvements (like jumping over batches) can extend coverage but also may miss smth before if the jumping to indices is too large.

### CODE REVIEW

File: YoutubeExplode/Playlists/PlaylistClient.cs [hunk 1]
```diff
@@ -83,13 +84,22 @@ public async IAsyncEnumerable<Batch<PlaylistVideo>> GetVideoBatchesAsync(
...
+                    lastVideoId,
+                    lastVideoIndex,
+                    visitorData,
+                    cancellationToken
+                );
+            }
+            catch (PlaylistUnavailableException)
+            {
+                // Stop enumeration if the playlist becomes unavailable
+                yield break;
```
Comment (Tyrrrz) [inline YoutubeExplode/Playlists/PlaylistClient.cs]: Shouldn't we try the next batch still, until it's empty?
